AllCops:
  Exclude:
    - vendor/**/*

inherit_from: .rubocop_todo.yml

Style/AndOr:
  EnforcedStyle: conditionals

Style/SignalException:
  EnforcedStyle: only_raise

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/AlignHash:
  EnforcedHashRocketStyle: table
