# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{character}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Piotr Solnica"]
  s.date = %q{2011-04-07}
  s.description = %q{Add validatable attributes to your ruby objects}
  s.email = ["piotr@rubyverse.com"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "character.gemspec",
    "lib/character.rb",
    "lib/character/attributes.rb",
    "lib/character/attributes/attribute.rb",
    "lib/character/attributes/boolean.rb",
    "lib/character/attributes/date.rb",
    "lib/character/attributes/date_time.rb",
    "lib/character/attributes/decimal.rb",
    "lib/character/attributes/float.rb",
    "lib/character/attributes/integer.rb",
    "lib/character/attributes/numeric.rb",
    "lib/character/attributes/object.rb",
    "lib/character/attributes/string.rb",
    "lib/character/attributes/time.rb",
    "lib/character/attributes/typecast/numeric.rb",
    "lib/character/attributes/typecast/time.rb",
    "spec/integration/attributes/attribute_spec.rb",
    "spec/integration/attributes/attributes_spec.rb",
    "spec/integration/attributes/const_missing_spec.rb",
    "spec/shared/attribute_spec.rb",
    "spec/spec_helper.rb",
    "spec/unit/attributes/boolean_spec.rb",
    "spec/unit/attributes/class_methods/determine_type_spec.rb",
    "spec/unit/attributes/date_spec.rb",
    "spec/unit/attributes/date_time_spec.rb",
    "spec/unit/attributes/decimal_spec.rb",
    "spec/unit/attributes/float_spec.rb",
    "spec/unit/attributes/integer_spec.rb",
    "spec/unit/attributes/numeric/class_methods/descendants_spec.rb",
    "spec/unit/attributes/object/class_methods/descendants_spec.rb",
    "spec/unit/attributes/string_spec.rb",
    "spec/unit/attributes/time_spec.rb"
  ]
  s.homepage = %q{https://github.com/solnic/character}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Add validatable attributes to your ruby objects}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<character>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.4.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.4.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.4.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.4.0"])
    else
      s.add_dependency(%q<character>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rspec>, ["~> 2.4.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rspec>, ["~> 2.4.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rspec>, ["~> 2.4.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rspec>, ["~> 2.4.0"])
    end
  else
    s.add_dependency(%q<character>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rspec>, ["~> 2.4.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rspec>, ["~> 2.4.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rspec>, ["~> 2.4.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rspec>, ["~> 2.4.0"])
  end
end

